export const IS_LOADING = "IS_LOADING";
export const IS_NOT_LOADING = "IS_NOT_LOADING";

export const ADD_FEATURE_FLAG = "ADD_FEATURE_FLAG";
export const FETCH_ALL_FLAGS = "FETCH_ALL_FLAGS";
export const TOGGLE_FEATURE_FLAG = "TOGGLE_FEATURE_FLAG";